# #-------- class start
renderer = class  index extends bamboosnowtemplate
  #
  # section storyHeadMatter
  #
  storyHeadMatter: =>
    #T.link rel: "stylesheet", href: "bootstrap.css", type: "text/regcss"
    T.script type:"text/javascript", """// Generated by CoffeeScript 1.12.7
(function() {
  window.onload = function() {
    var i, len, parseSrc, shifts, style, styles, x;
    styles = Array.prototype.filter.call(document.querySelectorAll('link, style'), function(node) {
      return node.getAttribute('type') === 'text/csshift';
    });
    shifts = window.colorTransforms;
    parseSrc = function(src, xhr) {
      var replacer, shift, style;
      if (xhr && xhr.readyState === 4 || !xhr) {
        for (shift in shifts) {
          replacer = shifts[shift];
          src = src.replace(RegExp(shift, 'g'), replacer);
        }
        style = document.createElement('style');
        style.type = 'text/css';
        if (style.styleSheet) {
          style.styleSheet.cssText = src;
        } else {
          style.appendChild(document.createTextNode(src));
        }
        document.head.appendChild(style);
      }
    };
    for (i = 0, len = styles.length; i < len; i++) {
      style = styles[i];
      if (style.href) {
        x = new XMLHttpRequest;
        x.onreadystatechange = function() {
          parseSrc(x.responseText, x);
        };
        x.open('GET', style.href, true);
        x.send();
      } else {
        parseSrc(style.innerHTML);
      }
    }
  };

}).call(this);
"""
    return
  # 
  # section html
  # 
  # 
  # section bamboosnow_body
  # 
  # 
  # section cover
  # 
  # 
  # section footer
  # 
  # 
  # section sidebarTop
  # 
  # 
  # section sidebar
  # 
  # 
  # section storybar
  # 
  # 
  # section bloviation
  # 
  bloviation: =>
    T.div "#bloviation.contents", =>
      T.p =>
        T.text "Life is just a bowl of cherries -.col-1, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7, .col-8, .col-9, .col-10, .col-11, .col-12, .col, .col-auto, .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm, .col-sm-auto, .col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12, .col-md, .col-md-auto, .col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg, .col-lg-auto, .col-xl-1, .col-xl-2, .col-xl-3, .col-xl-4, .col-xl-5, .col-xl-6, .col-xl-7, .col-xl-8, .col-xl-9, .col-xl-10, .col-xl-11, .col-xl-12, "
        T.a href: "/announcement/two-years-with-bamboo-snow.html", => T.raw "incredible life with Bamboo Snow."
      T.p "Life is just a bowl of cherries -.col-1, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7, .col-8, .col-9, .col-10, .col-11, .col-12, .col, .col-auto, .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm, .col-sm-auto, .col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12, .col-md, .col-md-auto, .col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg, .col-lg-auto, .col-xl-1, .col-xl-2, .col-xl-3, .col-xl-4, .col-xl-5, .col-xl-6, .col-xl-7, .col-xl-8, .col-xl-9, .col-xl-10, .col-xl-11, .col-xl-12, "
      T.p "Life is just a bowl of cherries -.col-1, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7, .col-8, .col-9, .col-10, .col-11, .col-12, .col, .col-auto, .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm, .col-sm-auto, .col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12, .col-md, .col-md-auto, .col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg, .col-lg-auto, .col-xl-1, .col-xl-2, .col-xl-3, .col-xl-4, .col-xl-5, .col-xl-6, .col-xl-7, .col-xl-8, .col-xl-9, .col-xl-10, .col-xl-11, .col-xl-12, "
  # 
  # section sidecar
  # 
  # 
  # section fb_status
  # 
  # 
  # section logoimg
  # 
  allMeta = [[["name","author"],["content","James A. Hinds: Bubba Baba Bamboo Jim"]],[["http-equiv","Content-Type"],["content","text/html"],["charset","UTF-8"]],[["name","viewport"],["content","width=device-width, initial-scale=1"]],[["name","description"],["content","All that is known about Bamboo Snow"]],[["name","keywords"],["content","bamboo snow,dinoderus minutus,absorbant,dessicant,organic,bamboo byproduct,bamboo"]],[["property","fb:admins"],["content","263369930812986"]],[["name","msapplication-TileColor"],["content","#ffffff"]],[["name","msapplication-TileImage"],["content","/assets/icons/ms-icon-144x144.png"]],[["name","theme-color"],["content","#ffffff"]]]
  htmlTitle = "Bamboo Snow: The Amazing Substance"
#-------- class end
#
#
db = {} unless db
# ------- db start
#

db[id="bamboosnow/products/blocks"] =
  title: "blocks"
  slug: "blocks"
  category: "products"
  site: "bamboosnow"
  accepted: false
  index: false
  sourcePath: ""
  headlines: []
  tags: []
  snippets: "{\"first name\":\"first name\"}"
  memberOf: []
  created: "2018-06-21T23:00:47.977Z"
  lastEdited: "2018-06-21T23:00:47.978Z"
  published: "2018-06-21T23:00:47.978Z"
  embargo: "2018-06-21T23:00:47.978Z"
  captureDate: "2018-06-21T23:00:47.978Z"
  TimeStamp: 1529622047978
  debug: ""
  author: "James A. Hinds: Bubba Baba Bamboo Jim"
  id: "bamboosnow/products/blocks"
  name: "blocks"
#